# permissions for end users to view tonglinkqclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tonglinkqcluster-viewer-role
rules:
- apiGroups:
  - tlq.tongtech.com
  resources:
  - tonglinkqclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tlq.tongtech.com
  resources:
  - tonglinkqclusters/status
  verbs:
  - get
